DROP TRIGGER IF EXISTS `ultima_posizione`;
DELIMITER //
CREATE TRIGGER `ultima_posizione` AFTER INSERT ON `points`
FOR EACH ROW BEGIN

    DELETE FROM points_ultimi WHERE PNT_AID=NEW.PNT_AID;

    INSERT INTO points_ultimi 
        (`PNT_AID`, `PNT_DTA`, `PNT_SES`, `PNT_LAT`, `PNT_LON`, `PNT_SPEED`, `PNT_BEARING`, `PNT_SIGNAL`, `PNT_PROVIDER`, `PNT_SATS`, `PNT_SATSFIX`) 
        VALUES 
        (NEW.PNT_AID, NEW.PNT_DTA, NEW.PNT_SES, NEW.PNT_LAT, NEW.PNT_LON, NEW.PNT_SPEED, NEW.PNT_BEARING, NEW.PNT_SIGNAL, NEW.PNT_PROVIDER, NEW.PNT_SATS, NEW.PNT_SATSFIX) 
    ;
END
//
